-- One countywide tax profile per Iowa county (all 99 are 6% state + 1% local option)
INSERT INTO "tax_profiles" ("id", "name", "state_code", "state_rate", "local_rate", "municipality", "county", "taxable_labor", "is_default", "created_at")
SELECT v.id, v.name, v.state_code, v.state_rate, v.local_rate, v.municipality, v.county, v.taxable_labor, v.is_default, v.created_at
FROM (VALUES
  (gen_random_uuid()::text, 'Adair County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Adair', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Adams County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Adams', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Allamakee County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Allamakee', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Appanoose County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Appanoose', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Audubon County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Audubon', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Benton County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Benton', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Black Hawk County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Black Hawk', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Boone County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Boone', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Bremer County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Bremer', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Buchanan County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Buchanan', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Buena Vista County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Buena Vista', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Butler County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Butler', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Calhoun County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Calhoun', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Carroll County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Carroll', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Cass County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Cass', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Cedar County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Cedar', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Cerro Gordo County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Cerro Gordo', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Cherokee County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Cherokee', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Chickasaw County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Chickasaw', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Clarke County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Clarke', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Clay County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Clay', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Clayton County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Clayton', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Clinton County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Clinton', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Crawford County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Crawford', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Dallas County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Dallas', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Davis County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Davis', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Decatur County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Decatur', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Delaware County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Delaware', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Des Moines County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Des Moines', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Dickinson County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Dickinson', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Dubuque County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Dubuque', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Emmet County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Emmet', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fayette County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Fayette', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Floyd County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Floyd', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Franklin County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Franklin', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fremont County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Fremont', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Greene County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Greene', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Grundy County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Grundy', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Guthrie County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Guthrie', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Hamilton County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Hamilton', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Hancock County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Hancock', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Hardin County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Hardin', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Harrison County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Harrison', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Henry County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Henry', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Howard County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Howard', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Humboldt County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Humboldt', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Ida County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Ida', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Iowa County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Iowa', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Jackson County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Jackson', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Jasper County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Jasper', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Jefferson County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Jefferson', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Johnson County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Johnson', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Jones County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Jones', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Keokuk County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Keokuk', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Kossuth County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Kossuth', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Lee County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Lee', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Linn County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Linn', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Louisa County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Louisa', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Lucas County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Lucas', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Lyon County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Lyon', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Madison County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Madison', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Mahaska County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Mahaska', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Marion County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Marion', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Marshall County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Marshall', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Mills County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Mills', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Mitchell County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Mitchell', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Monona County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Monona', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Monroe County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Monroe', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Montgomery County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Montgomery', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Muscatine County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Muscatine', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'O''Brien County, IA', 'IA', 0.06, 0.01, 'Countywide', 'O''Brien', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Osceola County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Osceola', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Page County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Page', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Palo Alto County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Palo Alto', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Plymouth County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Plymouth', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Pocahontas County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Pocahontas', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Polk County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Polk', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Pottawattamie County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Pottawattamie', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Poweshiek County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Poweshiek', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Ringgold County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Ringgold', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Sac County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Sac', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Scott County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Scott', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Shelby County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Shelby', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Sioux County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Sioux', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Story County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Story', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Tama County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Tama', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Taylor County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Taylor', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Union County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Union', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Van Buren County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Van Buren', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Wapello County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Wapello', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Warren County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Warren', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Washington County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Washington', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Wayne County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Wayne', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Webster County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Webster', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Winnebago County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Winnebago', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Winneshiek County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Winneshiek', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Woodbury County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Woodbury', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Worth County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Worth', false, false, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Wright County, IA', 'IA', 0.06, 0.01, 'Countywide', 'Wright', false, false, CURRENT_TIMESTAMP)
) AS v(id, name, state_code, state_rate, local_rate, municipality, county, taxable_labor, is_default, created_at)
WHERE NOT EXISTS (SELECT 1 FROM "tax_profiles" t WHERE t."name" = v.name);
