-- Local option sales tax is remitted by county in Iowa; add county to tax profiles
ALTER TABLE "tax_profiles" ADD COLUMN "county" TEXT;

-- Backfill counties for the seeded Iowa municipalities
UPDATE "tax_profiles" SET "county" = CASE "municipality"
  WHEN 'Des Moines' THEN 'Polk'
  WHEN 'Ankeny' THEN 'Polk'
  WHEN 'West Des Moines' THEN 'Polk'
  WHEN 'Urbandale' THEN 'Polk'
  WHEN 'Johnston' THEN 'Polk'
  WHEN 'Clive' THEN 'Polk'
  WHEN 'Windsor Heights' THEN 'Polk'
  WHEN 'Pleasant Hill' THEN 'Polk'
  WHEN 'Altoona' THEN 'Polk'
  WHEN 'Bondurant' THEN 'Polk'
  WHEN 'Grimes' THEN 'Polk'
  WHEN 'Polk City' THEN 'Polk'
  WHEN 'Mitchellville' THEN 'Polk'
  WHEN 'Norwalk' THEN 'Warren'
  WHEN 'Indianola' THEN 'Warren'
  WHEN 'Carlisle' THEN 'Warren'
  WHEN 'Waukee' THEN 'Dallas'
  WHEN 'Adel' THEN 'Dallas'
  WHEN 'Perry' THEN 'Dallas'
  WHEN 'Woodward' THEN 'Dallas'
  WHEN 'Winterset' THEN 'Madison'
  WHEN 'Cedar Rapids' THEN 'Linn'
  WHEN 'Marion' THEN 'Linn'
  WHEN 'Iowa City' THEN 'Johnson'
  WHEN 'Coralville' THEN 'Johnson'
  WHEN 'North Liberty' THEN 'Johnson'
  WHEN 'Davenport' THEN 'Scott'
  WHEN 'Bettendorf' THEN 'Scott'
  WHEN 'Sioux City' THEN 'Woodbury'
  WHEN 'Waterloo' THEN 'Black Hawk'
  WHEN 'Cedar Falls' THEN 'Black Hawk'
  WHEN 'Ames' THEN 'Story'
  WHEN 'Dubuque' THEN 'Dubuque'
  WHEN 'Council Bluffs' THEN 'Pottawattamie'
  WHEN 'Mason City' THEN 'Cerro Gordo'
  WHEN 'Burlington' THEN 'Des Moines'
  WHEN 'Clinton' THEN 'Clinton'
  WHEN 'Ottumwa' THEN 'Wapello'
  WHEN 'Fort Dodge' THEN 'Webster'
  WHEN 'Marshalltown' THEN 'Marshall'
  WHEN 'Muscatine' THEN 'Muscatine'
  WHEN 'Keokuk' THEN 'Lee'
  ELSE "county"
END;
